name: Publish
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.ecr-login.outputs.registry }}/yamachu/host-tunnelto:latest
          push: true
